/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import bibliotecaclon1.Alumno;
import bibliotecaclon1.AlumnoData;
import bibliotecaclon1.Conexion;
import bibliotecaclon1.Libro;
import bibliotecaclon1.LibroData;
import bibliotecaclon1.Prestamo;
import bibliotecaclon1.PrestamoData;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
/**
 *
 * @author santi
 */
public class AgregarPrestamo2 extends java.awt.Dialog {

    /**
     * Creates new form AgregarPrestamo2
     */
    public AgregarPrestamo2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setBounds(550, 142, 700, 600);
        agregarComboAlumno();
        agregarComboLibro();
        AutoCompleteDecorator.decorate(jcbAlumno);
        AutoCompleteDecorator.decorate(jcbLibro);
    }

    private void agregarComboAlumno(){
        try{
            Conexion con = new Conexion("jdbc:mysql://localhost/biblioteca","root","");
            AlumnoData ad = new AlumnoData(con);
            List<Alumno> listA = ad.obtenerAlumnos();
            for (int i = 0; i < listA.size(); i++){
                jcbAlumno.addItem(listA.get(i).getNombre());
            }
            
        }catch (Exception e){
          JOptionPane.showMessageDialog(null, "Fallo bro");
        }
    }
    
        private void agregarComboLibro(){
        try{
            Conexion con = new Conexion("jdbc:mysql://localhost/biblioteca","root","");
            LibroData ld = new LibroData(con);
            List<Libro> listA = ld.obtenerLibros();
            for (int i = 0; i < listA.size(); i++){
                jcbLibro.addItem(listA.get(i).getNombre());
            }
        }catch (Exception e){
          JOptionPane.showMessageDialog(null, "Fallo bro");
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlTitulo = new javax.swing.JLabel();
        jlAlumno = new javax.swing.JLabel();
        jlLibro = new javax.swing.JLabel();
        jlFechaDePrestamo = new javax.swing.JLabel();
        jlFechaDeDevolucion = new javax.swing.JLabel();
        jbGuardar = new javax.swing.JButton();
        jbCerrar = new javax.swing.JButton();
        jcbAlumno = new javax.swing.JComboBox<>();
        jcbLibro = new javax.swing.JComboBox<>();
        rsFechaPrestamo = new rojeru_san.componentes.RSDateChooser();
        rsFechaDevolucion = new rojeru_san.componentes.RSDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTitulo.setFont(new java.awt.Font("Harlow Solid Italic", 0, 48)); // NOI18N
        jlTitulo.setText("Agregar Prestamo");
        jPanel1.add(jlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        jlAlumno.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jlAlumno.setText("Alumno");
        jPanel1.add(jlAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jlLibro.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jlLibro.setText("Libro");
        jPanel1.add(jlLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jlFechaDePrestamo.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jlFechaDePrestamo.setText("Fecha de prestamo");
        jPanel1.add(jlFechaDePrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        jlFechaDeDevolucion.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jlFechaDeDevolucion.setText("Fecha de devolucion");
        jPanel1.add(jlFechaDeDevolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        jbGuardar.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jbGuardar.setText("Guardar y cerrar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jbGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 200, 40));

        jbCerrar.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jbCerrar.setText("Cerrar");
        jbCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(jbCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 120, 40));

        jcbAlumno.setEditable(true);
        jcbAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAlumnoActionPerformed(evt);
            }
        });
        jPanel1.add(jcbAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 230, -1));

        jcbLibro.setEditable(true);
        jPanel1.add(jcbLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 230, -1));
        jPanel1.add(rsFechaPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, 30));
        jPanel1.add(rsFechaDevolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/light-violet-color-wallpaper-4.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
        String nombreAlumno = jcbAlumno.getItemAt(jcbAlumno.getSelectedIndex());
        String nombreLibro = jcbLibro.getItemAt(jcbLibro.getSelectedIndex());
        java.util.Date date1= rsFechaPrestamo.getDatoFecha();
        java.util.Date date2= rsFechaDevolucion.getDatoFecha();
        java.sql.Date sqlDate = new java.sql.Date(date1.getTime());
        java.sql.Date sqlDate2 = new java.sql.Date(date2.getTime());
        if (sqlDate.compareTo(java.sql.Date.valueOf(LocalDate.now())) <= 0){
            Conexion con = null;
            try {
                con = new Conexion("jdbc:mysql://localhost/biblioteca","root","");
                LibroData ld = new LibroData(con);
                AlumnoData ad = new AlumnoData(con);
                PrestamoData pd = new PrestamoData(con);

                Libro libro = ld.getLibroByName(nombreLibro);
                Alumno alumno = ad.getAlumnoByName(nombreAlumno);
                Prestamo p = new Prestamo(alumno.getId(),libro.getId(),sqlDate,sqlDate2);
                pd.guardarPrestamo(p);
                JOptionPane.showMessageDialog(null, "Felicidades, se ha agregado el prestamo correctamente");

                con.close();

                dispose();
            }
            catch (Exception e){
                System.out.println("Error " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "La fecha ingresada es invalida");
        }
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrarActionPerformed
        int msj = JOptionPane.showConfirmDialog(null,"Estas seguro de querer cerrar esta ventana?");
        if(JOptionPane.YES_OPTION == msj){
            dispose();
        }
    }//GEN-LAST:event_jbCerrarActionPerformed

    private void jcbAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AgregarPrestamo2 dialog = new AgregarPrestamo2(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbCerrar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JComboBox<String> jcbAlumno;
    private javax.swing.JComboBox<String> jcbLibro;
    private javax.swing.JLabel jlAlumno;
    private javax.swing.JLabel jlFechaDeDevolucion;
    private javax.swing.JLabel jlFechaDePrestamo;
    private javax.swing.JLabel jlLibro;
    private javax.swing.JLabel jlTitulo;
    private rojeru_san.componentes.RSDateChooser rsFechaDevolucion;
    private rojeru_san.componentes.RSDateChooser rsFechaPrestamo;
    // End of variables declaration//GEN-END:variables
}
