/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
import bibliotecaclon1.Alumno;
import bibliotecaclon1.AlumnoData;
import bibliotecaclon1.Conexion;
import bibliotecaclon1.Libro;
import bibliotecaclon1.LibroData;
import bibliotecaclon1.Prestamo;
import bibliotecaclon1.PrestamoData;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Ivan
 */
public class AgregarPrestamo extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarPrestamo
     */
    public AgregarPrestamo() {
        initComponents();
        AlumnoData.listarAlumnos(jcbAlumno);
        LibroData.listarLibros(jcbLibro);
        AutoCompleteDecorator.decorate(jcbAlumno);
        AutoCompleteDecorator.decorate(jcbLibro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jlTitulo = new javax.swing.JLabel();
        jlAlumno = new javax.swing.JLabel();
        jlLibro = new javax.swing.JLabel();
        jlFechaDePrestamo = new javax.swing.JLabel();
        jlFechaDeDevolucion = new javax.swing.JLabel();
        jbGuardar = new javax.swing.JButton();
        jbCerrar = new javax.swing.JButton();
        jcbAlumno = new javax.swing.JComboBox<>();
        jcbLibro = new javax.swing.JComboBox<>();
        rsFechaPrestamo = new rojeru_san.componentes.RSDateChooser();
        rsFechaDevolucion = new rojeru_san.componentes.RSDateChooser();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTitulo.setFont(new java.awt.Font("Harlow Solid Italic", 0, 48)); // NOI18N
        jlTitulo.setText("Agregar Prestamo");
        getContentPane().add(jlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        jlAlumno.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jlAlumno.setText("Alumno");
        getContentPane().add(jlAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jlLibro.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jlLibro.setText("Libro");
        getContentPane().add(jlLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jlFechaDePrestamo.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jlFechaDePrestamo.setText("Fecha de prestamo");
        getContentPane().add(jlFechaDePrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        jlFechaDeDevolucion.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jlFechaDeDevolucion.setText("Fecha de devolucion");
        getContentPane().add(jlFechaDeDevolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        jbGuardar.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jbGuardar.setText("Guardar y cerrar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jbGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 200, 40));

        jbCerrar.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jbCerrar.setText("Cerrar");
        jbCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 120, 40));

        jcbAlumno.setEditable(true);
        jcbAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(jcbAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 230, -1));

        jcbLibro.setEditable(true);
        getContentPane().add(jcbLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 230, -1));
        getContentPane().add(rsFechaPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, 30));
        getContentPane().add(rsFechaDevolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/light-violet-color-wallpaper-4.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_jbCerrarActionPerformed

    private void jcbAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbAlumnoActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
        String nombreAlumno = jcbAlumno.getItemAt(jcbAlumno.getSelectedIndex());
        String nombreLibro = jcbLibro.getItemAt(jcbLibro.getSelectedIndex());
        java.util.Date date1= rsFechaPrestamo.getDatoFecha();
        java.util.Date date2= rsFechaDevolucion.getDatoFecha();
        java.sql.Date sqlDate = new java.sql.Date(date1.getTime());  
        java.sql.Date sqlDate2 = new java.sql.Date(date2.getTime()); 
        if (sqlDate.compareTo(java.sql.Date.valueOf(LocalDate.now())) <= 0){
            Conexion con = null;
            try {
                con = new Conexion("jdbc:mysql://localhost/biblioteca","root","");
                    LibroData ld = new LibroData(con); 
                    AlumnoData ad = new AlumnoData(con);
                    PrestamoData pd = new PrestamoData(con);
                
                    Libro libro = ld.getLibroByName(nombreLibro);
                    Alumno alumno = ad.getAlumnoByName(nombreAlumno);
                    Prestamo p = new Prestamo(alumno.getId(),libro.getId(),sqlDate,sqlDate2);
                    pd.guardarPrestamo(p);
                    JOptionPane.showMessageDialog(null, "Felicidades la tenes re grande");
                
                    con.close();
                
                    dispose();
                }
            catch (Exception e){
                System.out.println("Error " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "La fecha ingresada es invalida");
        }
    }//GEN-LAST:event_jbGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbCerrar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JComboBox<String> jcbAlumno;
    private javax.swing.JComboBox<String> jcbLibro;
    private javax.swing.JLabel jlAlumno;
    private javax.swing.JLabel jlFechaDeDevolucion;
    private javax.swing.JLabel jlFechaDePrestamo;
    private javax.swing.JLabel jlLibro;
    private javax.swing.JLabel jlTitulo;
    private rojeru_san.componentes.RSDateChooser rsFechaDevolucion;
    private rojeru_san.componentes.RSDateChooser rsFechaPrestamo;
    // End of variables declaration//GEN-END:variables
}
