/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import static Vistas.ListaDeAlumnos.jtPrestamos;
import bibliotecaclon1.Alumno;
import bibliotecaclon1.AlumnoData;
import bibliotecaclon1.Conexion;
import com.sun.glass.events.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author santi
 */
public class AgregarAlumno2 extends java.awt.Dialog {

    /**
     * Creates new form AgregarAlumno2
     */
    public AgregarAlumno2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setBounds(433, 96, 700, 600);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfEmail = new javax.swing.JTextField();
        jbAgregarAlumno = new javax.swing.JButton();
        jlAgregarAlumno = new javax.swing.JLabel();
        jlNombreAlumno = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        tfNombreAlumno = new javax.swing.JTextField();
        jlRestriccionNombre = new javax.swing.JLabel();
        jlRestriccionEmail = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfEmailFocusLost(evt);
            }
        });
        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });
        jPanel1.add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 280, 30));

        jbAgregarAlumno.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jbAgregarAlumno.setText("Agregar y cerrar");
        jbAgregarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarAlumnoActionPerformed(evt);
            }
        });
        jPanel1.add(jbAgregarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 230, 40));

        jlAgregarAlumno.setFont(new java.awt.Font("Harlow Solid Italic", 0, 48)); // NOI18N
        jlAgregarAlumno.setText("Agregar Alumno");
        jPanel1.add(jlAgregarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        jlNombreAlumno.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jlNombreAlumno.setText("Nombre del alumno:");
        jPanel1.add(jlNombreAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jlEmail.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jlEmail.setText("Email:");
        jPanel1.add(jlEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 80, -1));

        tfNombreAlumno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNombreAlumnoFocusLost(evt);
            }
        });
        tfNombreAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreAlumnoActionPerformed(evt);
            }
        });
        tfNombreAlumno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNombreAlumnoKeyTyped(evt);
            }
        });
        jPanel1.add(tfNombreAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 278, 30));

        jlRestriccionNombre.setVisible(false);
        jlRestriccionNombre.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlRestriccionNombre.setForeground(new java.awt.Color(255, 51, 51));
        jlRestriccionNombre.setText("* Es necesario rellenar este campo");
        jPanel1.add(jlRestriccionNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, 20));

        jlRestriccionEmail.setVisible(false);
        jlRestriccionEmail.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlRestriccionEmail.setForeground(new java.awt.Color(255, 51, 51));
        jlRestriccionEmail.setText("* Es necesario rellenar este campo");
        jPanel1.add(jlRestriccionEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, -1));

        jButton2.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 90, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/light-violet-color-wallpaper-4.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 700, 620));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void tfEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEmailFocusLost
        if (tfEmail.getText().length() == 0){
            jlRestriccionEmail.setVisible(true);
        } else {
            jlRestriccionEmail.setVisible(false);
        }
    }//GEN-LAST:event_tfEmailFocusLost

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void jbAgregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarAlumnoActionPerformed

        Conexion con = null;
        try {
            con = new Conexion("jdbc:mysql://localhost/biblioteca","root","");
            if ((tfNombreAlumno.getText().length() < 30 && tfNombreAlumno.getText().length() > 0)&& (tfEmail.getText().length() < 50 && tfEmail.getText().length() > 0) ){
                Alumno alumno = new Alumno(tfNombreAlumno.getText(),tfEmail.getText());
                AlumnoData a = new AlumnoData(con);
                /*Alumno alumnoExistente = a.getAlumnoByMail(tfEmail.getText());
                if (tfEmail.getText() == alumnoExistente.getEmail()){ //Al parecer todo el tiempo son diferentes
                    JOptionPane.showMessageDialog(null, "Este alumno ya existe");
                } else {
                    a.guardarAlumno(alumno);
                    JOptionPane.showMessageDialog(null, "Felicidades el alumno se agrego correctamente");
                } Esto es para la condicion del email, pero no lo termine*/
                a.guardarAlumno(alumno);
                JOptionPane.showMessageDialog(null, "Felicidades el alumno se agrego correctamente");
                dispose();

            } else {
                JOptionPane.showMessageDialog(null, "Ocurrio un error al guardar el alumno, el nombre es demasido largo o el alumno ya existe");
                tfNombreAlumno.setText(null);
                tfEmail.setText(null);
            }
            con.close();
        } catch (Exception e){
            System.out.println("Error al instanciar la clase conexion" + e.getMessage());
        }
    }//GEN-LAST:event_jbAgregarAlumnoActionPerformed

    private void tfNombreAlumnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreAlumnoFocusLost
        if (tfNombreAlumno.getText().length() == 0){
            jlRestriccionNombre.setVisible(true);
        } else {
            jlRestriccionNombre.setVisible(false);
        }
    }//GEN-LAST:event_tfNombreAlumnoFocusLost

    private void tfNombreAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreAlumnoActionPerformed

    private void tfNombreAlumnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombreAlumnoKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c != KeyEvent.VK_SPACE)){
            evt.consume();
            jlRestriccionNombre.setVisible(true);
        }
    }//GEN-LAST:event_tfNombreAlumnoKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AgregarAlumno2 dialog = new AgregarAlumno2(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAgregarAlumno;
    private javax.swing.JLabel jlAgregarAlumno;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlNombreAlumno;
    private javax.swing.JLabel jlRestriccionEmail;
    private javax.swing.JLabel jlRestriccionNombre;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNombreAlumno;
    // End of variables declaration//GEN-END:variables
}
