/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import bibliotecaclon1.Conexion;
import bibliotecaclon1.Libro;
import bibliotecaclon1.LibroData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author biane
 */
public class AgregarLibro extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListaDeAlumnos
     */
    public AgregarLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlNombreLibro = new javax.swing.JLabel();
        jlCantidad = new javax.swing.JLabel();
        jlGenero = new javax.swing.JLabel();
        jlAutor = new javax.swing.JLabel();
        tfGenero = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        tfCantidad = new javax.swing.JTextField();
        tfAutor = new javax.swing.JTextField();
        jbAgregarLibro = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setText("Agregar Libro");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        jlNombreLibro.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jlNombreLibro.setText("Nombre del libro:");
        getContentPane().add(jlNombreLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 220, 50));

        jlCantidad.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jlCantidad.setText("Cantidad:");
        getContentPane().add(jlCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 140, -1));

        jlGenero.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jlGenero.setText("Género:");
        getContentPane().add(jlGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jlAutor.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jlAutor.setText("Autor:");
        getContentPane().add(jlAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        tfGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfGeneroActionPerformed(evt);
            }
        });
        getContentPane().add(tfGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 430, 30));

        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });
        getContentPane().add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 430, 30));
        getContentPane().add(tfCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 430, 30));
        getContentPane().add(tfAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 430, 30));

        jbAgregarLibro.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jbAgregarLibro.setText("Agregar y cerrar");
        jbAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarLibroActionPerformed(evt);
            }
        });
        getContentPane().add(jbAgregarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 510, 220, 40));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/light-violet-color-wallpaper-4.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfGeneroActionPerformed

    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreActionPerformed

    private void jbAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarLibroActionPerformed
        // TODO add your handling code here:
        Conexion con = null;
        try {
            con = new Conexion("jdbc:mysql://localhost/biblioteca","root","");
            Libro libro = new Libro(tfNombre.getText(),Integer.parseInt(tfCantidad.getText()),tfGenero.getText(),tfAutor.getText());
            LibroData a = new LibroData(con);
            a.guardarLibro(libro);
            
            con.close();
            } catch (Exception e){
            System.out.println("Error al instanciar la clase conexion" + e.getMessage());
        }
        dispose();
    }//GEN-LAST:event_jbAgregarLibroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JButton jbAgregarLibro;
    private javax.swing.JLabel jlAutor;
    private javax.swing.JLabel jlCantidad;
    private javax.swing.JLabel jlGenero;
    private javax.swing.JLabel jlNombreLibro;
    private javax.swing.JTextField tfAutor;
    private javax.swing.JTextField tfCantidad;
    private javax.swing.JTextField tfGenero;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
