/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import bibliotecaclon1.Conexion;
import bibliotecaclon1.Libro;
import bibliotecaclon1.LibroData;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
/**
 *
 * @author santi
 */
public class AgregarLibro2 extends javax.swing.JPanel {

    /**
     * Creates new form AgregarLibro2
     */
    public AgregarLibro2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlNombreLibro = new javax.swing.JLabel();
        jlCantidad = new javax.swing.JLabel();
        jlGenero = new javax.swing.JLabel();
        jlAutor = new javax.swing.JLabel();
        tfGenero = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        tfCantidad = new javax.swing.JTextField();
        tfAutor = new javax.swing.JTextField();
        jbAgregarLibro = new javax.swing.JButton();
        jlRestriccionNombre = new javax.swing.JLabel();
        jlRestriccionGenero = new javax.swing.JLabel();
        jlRestriccionAutor = new javax.swing.JLabel();
        jbCerrar = new javax.swing.JButton();
        jlRestriccionCantidad = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();
        tfGenero1 = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Harlow Solid Italic", 0, 48)); // NOI18N
        jLabel1.setText("Agregar Libro");

        jlNombreLibro.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jlNombreLibro.setText("Nombre del libro:");

        jlCantidad.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jlCantidad.setText("Cantidad:");

        jlGenero.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jlGenero.setText("Género:");

        jlAutor.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jlAutor.setText("Autor:");

        tfGenero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfGeneroFocusLost(evt);
            }
        });
        tfGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfGeneroActionPerformed(evt);
            }
        });
        tfGenero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfGeneroKeyTyped(evt);
            }
        });

        tfNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNombreFocusLost(evt);
            }
        });
        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });
        tfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNombreKeyTyped(evt);
            }
        });

        tfCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCantidadFocusLost(evt);
            }
        });
        tfCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCantidadKeyTyped(evt);
            }
        });

        tfAutor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfAutorFocusLost(evt);
            }
        });
        tfAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfAutorKeyTyped(evt);
            }
        });

        jbAgregarLibro.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jbAgregarLibro.setText("Agregar y cerrar");
        jbAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarLibroActionPerformed(evt);
            }
        });

        jlRestriccionNombre.setVisible(false);
        jlRestriccionNombre.setForeground(new java.awt.Color(255, 51, 51));
        jlRestriccionNombre.setText("* Es necesario rellenar este campo");

        jlRestriccionGenero.setVisible(false);
        jlRestriccionGenero.setForeground(new java.awt.Color(255, 51, 51));
        jlRestriccionGenero.setText("* Es necesario rellenar este campo");

        jlRestriccionAutor.setVisible(false);
        jlRestriccionAutor.setForeground(new java.awt.Color(255, 51, 51));
        jlRestriccionAutor.setText("* Es necesario rellenar este campo");

        jbCerrar.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jbCerrar.setText("Cerrar");
        jbCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrarActionPerformed(evt);
            }
        });

        jlRestriccionCantidad.setVisible(false);
        jlRestriccionCantidad.setForeground(new java.awt.Color(255, 51, 51));
        jlRestriccionCantidad.setText("* Es necesario rellenar este campo");

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/light-violet-color-wallpaper-4.jpg"))); // NOI18N

        tfGenero1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfGenero1FocusLost(evt);
            }
        });
        tfGenero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfGenero1ActionPerformed(evt);
            }
        });
        tfGenero1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfGenero1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(231, Short.MAX_VALUE)
                .addComponent(tfGenero1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(200, 200, 200)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jlNombreLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(230, 230, 230)
                            .addComponent(jlRestriccionNombre))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jlCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(70, 70, 70)
                            .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(230, 230, 230)
                            .addComponent(jlRestriccionCantidad))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jlGenero)
                            .addGap(125, 125, 125)
                            .addComponent(tfGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(230, 230, 230)
                            .addComponent(jlRestriccionGenero))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jlAutor)
                            .addGap(135, 135, 135)
                            .addComponent(tfAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(230, 230, 230)
                            .addComponent(jlRestriccionAutor))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(130, 130, 130)
                            .addComponent(jbCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(230, 230, 230)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(330, 330, 330)
                            .addComponent(jbAgregarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(281, Short.MAX_VALUE)
                .addComponent(tfGenero1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(259, 259, 259))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jLabel1)
                            .addGap(19, 19, 19)
                            .addComponent(jlNombreLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jlRestriccionNombre)
                            .addGap(15, 15, 15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlCantidad)
                                .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(10, 10, 10)
                            .addComponent(jlRestriccionCantidad)
                            .addGap(15, 15, 15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlGenero)
                                .addComponent(tfGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlRestriccionGenero)
                            .addGap(15, 15, 15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlAutor)
                                .addComponent(tfAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(10, 10, 10)
                            .addComponent(jlRestriccionAutor)
                            .addGap(45, 45, 45)
                            .addComponent(jbCerrar))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(130, 130, 130)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(460, 460, 460)
                            .addComponent(jbAgregarLibro))
                        .addComponent(jLabelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfGeneroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfGeneroFocusLost
        if (tfGenero.getText().length() == 0){
            jlRestriccionGenero.setVisible(true);
        } else {
            jlRestriccionGenero.setVisible(false);
        }
    }//GEN-LAST:event_tfGeneroFocusLost

    private void tfGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfGeneroActionPerformed

    private void tfGeneroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfGeneroKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c != KeyEvent.VK_SPACE)){
            evt.consume();
        }
    }//GEN-LAST:event_tfGeneroKeyTyped

    private void tfNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNombreFocusLost
        if (tfNombre.getText().length() == 0){
            jlRestriccionNombre.setVisible(true);
        } else {
            jlRestriccionNombre.setVisible(false);
        }
    }//GEN-LAST:event_tfNombreFocusLost

    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        // TODO add your handling code here:
        if (tfNombre.getText().length() > 1){
            jlRestriccionNombre.setVisible(true);
        } else {
            jlRestriccionNombre.setVisible(false);
        }
    }//GEN-LAST:event_tfNombreActionPerformed

    private void tfNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombreKeyTyped

    }//GEN-LAST:event_tfNombreKeyTyped

    private void tfCantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCantidadFocusLost
        if (tfCantidad.getText().length() == 0){
            jlRestriccionCantidad.setVisible(true);
        } else {
            jlRestriccionCantidad.setVisible(false);
        }
    }//GEN-LAST:event_tfCantidadFocusLost

    private void tfCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCantidadKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9'){
            evt.consume();
        }
    }//GEN-LAST:event_tfCantidadKeyTyped

    private void tfAutorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAutorFocusLost
        if (tfAutor.getText().length() == 0){
            jlRestriccionAutor.setVisible(true);
        } else {
            jlRestriccionAutor.setVisible(false);
        }
    }//GEN-LAST:event_tfAutorFocusLost

    private void tfAutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAutorKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c != KeyEvent.VK_SPACE)){
            evt.consume();
        }
    }//GEN-LAST:event_tfAutorKeyTyped

    private void jbAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarLibroActionPerformed
        // TODO add your handling code here:

        try {
            if (tfNombre.getText().length() > 0 && tfCantidad.getText().length() > 0 && tfGenero.getText().length() > 0 && tfAutor.getText().length() > 0 ){
                Conexion con = null;
                con = new Conexion("jdbc:mysql://localhost/biblioteca","root","");
                Libro libro = new Libro(tfNombre.getText(),Integer.parseInt(tfCantidad.getText()),tfGenero.getText(),tfAutor.getText());
                LibroData a = new LibroData(con);
                a.guardarLibro(libro);
                JOptionPane.showMessageDialog(null, "Felicidades, libro agregado");

                con.close();
                //dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Ocurrio un error al guardar el libro, un campo quedo sin rellenar");
            }
        } catch (Exception e){
            System.out.println("Error al instanciar la clase conexion" + e.getMessage());
            JOptionPane.showMessageDialog(null,"No se pudo guardar el libro, intente nuevamente");
        }
    }//GEN-LAST:event_jbAgregarLibroActionPerformed

    private void jbCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrarActionPerformed
        //dispose();
    }//GEN-LAST:event_jbCerrarActionPerformed

    private void tfGenero1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfGenero1FocusLost
        if (tfGenero.getText().length() == 0){
            jlRestriccionGenero.setVisible(true);
        } else {
            jlRestriccionGenero.setVisible(false);
        }
    }//GEN-LAST:event_tfGenero1FocusLost

    private void tfGenero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfGenero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfGenero1ActionPerformed

    private void tfGenero1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfGenero1KeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c != KeyEvent.VK_SPACE)){
            evt.consume();
        }
    }//GEN-LAST:event_tfGenero1KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JButton jbAgregarLibro;
    private javax.swing.JButton jbCerrar;
    private javax.swing.JLabel jlAutor;
    private javax.swing.JLabel jlCantidad;
    private javax.swing.JLabel jlGenero;
    private javax.swing.JLabel jlNombreLibro;
    private javax.swing.JLabel jlRestriccionAutor;
    private javax.swing.JLabel jlRestriccionCantidad;
    private javax.swing.JLabel jlRestriccionGenero;
    private javax.swing.JLabel jlRestriccionNombre;
    private javax.swing.JTextField tfAutor;
    private javax.swing.JTextField tfCantidad;
    private javax.swing.JTextField tfGenero;
    private javax.swing.JTextField tfGenero1;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
