/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import bibliotecaclon1.Alumno;
import bibliotecaclon1.AlumnoData;
import bibliotecaclon1.Conexion;

/**
 *
 * @author santi
 */
public class FormularioCliente2 extends java.awt.Dialog {

    /**
     * Creates new form FormularioCliente2
     */
    public FormularioCliente2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_nombre = new javax.swing.JLabel();
        lb_email = new javax.swing.JLabel();
        bt_guardarAlumno = new javax.swing.JButton();
        tf_nombreAlumno = new javax.swing.JTextField();
        tf_emailAlumno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_nombre.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        lb_nombre.setText("Nombre:");
        jPanel1.add(lb_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 100, 28));

        lb_email.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        lb_email.setText("Email:");
        jPanel1.add(lb_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, 27));

        bt_guardarAlumno.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        bt_guardarAlumno.setText("Guardar y Cerrar");
        bt_guardarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardarAlumnoActionPerformed(evt);
            }
        });
        jPanel1.add(bt_guardarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 210, 40));

        tf_nombreAlumno.setName("tf_nombreAlumno"); // NOI18N
        tf_nombreAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombreAlumnoActionPerformed(evt);
            }
        });
        jPanel1.add(tf_nombreAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 380, 30));
        jPanel1.add(tf_emailAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 380, 30));

        jLabel1.setFont(new java.awt.Font("Harlow Solid Italic", 0, 48)); // NOI18N
        jLabel1.setText("Formulario de Alumno");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        jButton1.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 100, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/light-violet-color-wallpaper-4.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 600));

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void bt_guardarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarAlumnoActionPerformed
        // TODO add your handling code here:
        Alumno a = new Alumno(tf_nombreAlumno.getText(),tf_emailAlumno.getText());
        try {
            Conexion con = new Conexion("jdbc:mysql://localhost/biblioteca","root","");

            AlumnoData alumnoData = new AlumnoData(con);

            alumnoData.guardarAlumno(a);
            con.close();
        }
        catch (Exception e){
            System.out.println("Error al instanciar la clase conexion" + e.getMessage());
        }
    }//GEN-LAST:event_bt_guardarAlumnoActionPerformed

    private void tf_nombreAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombreAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombreAlumnoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormularioCliente2 dialog = new FormularioCliente2(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_guardarAlumno;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_email;
    private javax.swing.JLabel lb_nombre;
    private javax.swing.JTextField tf_emailAlumno;
    private javax.swing.JTextField tf_nombreAlumno;
    // End of variables declaration//GEN-END:variables
}
