/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import static Vistas.ListaDePrestamos.jScrollPane1;
import static Vistas.ListaDePrestamos.jtPrestamos;
import bibliotecaclon1.Alumno;
import bibliotecaclon1.AlumnoData;
import bibliotecaclon1.Conexion;
import bibliotecaclon1.Libro;
import bibliotecaclon1.LibroData;
import bibliotecaclon1.Prestamo;
import bibliotecaclon1.PrestamoData;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;


/**
 *
 * @author santi
 */
public class ListaDePrestamos2 extends java.awt.Dialog {

    /**
     * Creates new form ListaDePrestamos2
     */
    public ListaDePrestamos2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setBounds(433, 96, 700, 600);
        try{
            Conexion con = new Conexion("jdbc:mysql://localhost/biblioteca","root","");
            PrestamoData pd = new PrestamoData(con);
            List<Prestamo> lista = pd.obtenerPrestamos();
            
            mostrarLista(lista);
            
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "No se pudo cargar la tabla " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlAListaPrestamos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPrestamos = new javax.swing.JTable();
        jbCerrar = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jbAgregar = new javax.swing.JButton();
        jbBorrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlAListaPrestamos.setFont(new java.awt.Font("Harlow Solid Italic", 0, 48)); // NOI18N
        jlAListaPrestamos.setText(" Lista de Préstamos");
        jPanel1.add(jlAListaPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 390, -1));

        jtPrestamos.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jtPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Alumno", "Libro", "Fecha de prestamo", "Fecha de devolucion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtPrestamos.setRowHeight(30);
        jScrollPane1.setViewportView(jtPrestamos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 680, 440));

        jbCerrar.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jbCerrar.setText("Cerrar");
        jbCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(jbCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, -1, -1));

        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/5x5-02.png"))); // NOI18N
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 30, -1));

        jbAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/5x5_Mesa de trabajo 1.png"))); // NOI18N
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(jbAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 30, -1));

        jbBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/5x5-03.png"))); // NOI18N
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(jbBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 30, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/refrescar (3).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/light-violet-color-wallpaper-4.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jbCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_jbCerrarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        BuscarPrestamo2 dialog = new BuscarPrestamo2(new java.awt.Frame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        AgregarPrestamo2 dialog = new AgregarPrestamo2(new java.awt.Frame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jtPrestamos.getModel();
        try{
            if (jtPrestamos.getSelectedRow() != 1){
                DefaultTableModel tm = (DefaultTableModel) jtPrestamos.getModel();
                String nombreAlumno =String.valueOf(tm.getValueAt(jtPrestamos.getSelectedRow(),0));
                String nombreLibro =String.valueOf(tm.getValueAt(jtPrestamos.getSelectedRow(),1));
                Conexion con = new Conexion("jdbc:mysql://localhost/biblioteca","root","");
                PrestamoData pd = new PrestamoData(con);
                AlumnoData ad = new AlumnoData(con);
                LibroData ld = new LibroData(con);
                //
                Alumno alumno = ad.getAlumnoByName(nombreAlumno);
                Libro libro = ld.getLibroByName(nombreLibro);
                Prestamo prestamoBorrar = pd.obtenerPrestamoPorLibroAndAlumno(alumno, libro);
                pd.borrarPrestamo(prestamoBorrar);
                dtm.removeRow(jtPrestamos.getSelectedRow());
            } else {
                JOptionPane.showMessageDialog(null, "No has seleccionado ningun prestamo");
            }
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "No has seleccionado ningun prestamo");
        }
    }//GEN-LAST:event_jbBorrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            Conexion con = new Conexion("jdbc:mysql://localhost/biblioteca","root","");
            PrestamoData op = new PrestamoData(con);
            List<Prestamo> lista = op.obtenerPrestamos();

            mostrarLista(lista);

        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "No se pudo cargar la tabla " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void mostrarLista(List<Prestamo> lista){
        try{
            Conexion con = new Conexion("jdbc:mysql://localhost/biblioteca","root","");
            String matris[][] = new String[lista.size()][4];
            AlumnoData ad = new AlumnoData(con);
            LibroData ld = new LibroData(con);
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            
            for (int i = 0; i < lista.size(); i++){
                matris[i][0] = ad.getAlumnoById(lista.get(i).getIdAlumno()).getNombre();
                matris[i][1] = ld.getLibroById(lista.get(i).getIdLibro()).getNombre();
                matris[i][2] = sdf.format(lista.get(i).getFechaPrestamo());
                matris[i][3] = sdf.format(lista.get(i).getFechaDevolucion());
            }
            
            ListaDePrestamos2.jtPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            matris,
            new String [] {
                "Alumno", "Libro", "Fecha de prestamo", "Fecha de devolucion"
            }
            ));
            jtPrestamos.setRowHeight(30);
            jScrollPane1.setViewportView(jtPrestamos);
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "No funciono bro");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ListaDePrestamos2 dialog = new ListaDePrestamos2(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCerrar;
    private javax.swing.JLabel jlAListaPrestamos;
    public static javax.swing.JTable jtPrestamos;
    // End of variables declaration//GEN-END:variables
}
