/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import bibliotecaclon1.AlumnoData;
import bibliotecaclon1.Conexion;
import bibliotecaclon1.LibroData;
import bibliotecaclon1.Prestamo;
import bibliotecaclon1.PrestamoData;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;

/**
 *
 * @author biane
 */
public class ListaDePrestamos extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListaPrestamos
     */
    public ListaDePrestamos() {
        initComponents();
        try{
            Conexion con = new Conexion("jdbc:mysql://localhost/biblioteca","root","");
            PrestamoData pd = new PrestamoData(con);
            List<Prestamo> lista = pd.obtenerPrestamos();
            
            mostrarLista(lista);
            
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "No se pudo cargar la tabla " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        jlAListaPrestamos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPrestamos = new javax.swing.JTable();
        jbCerrar = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jbAgregar = new javax.swing.JButton();
        jbBorrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        button1.setLabel("button1");

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlAListaPrestamos.setFont(new java.awt.Font("Harlow Solid Italic", 0, 48)); // NOI18N
        jlAListaPrestamos.setText(" Lista de Préstamos");
        getContentPane().add(jlAListaPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 390, -1));

        jtPrestamos.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jtPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Alumno", "Libro", "Fecha de prestamo", "Fecha de devolucion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtPrestamos.setRowHeight(30);
        jScrollPane1.setViewportView(jtPrestamos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 670, 400));

        jbCerrar.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jbCerrar.setText("Cerrar");
        jbCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, -1, -1));

        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/5x5-02.png"))); // NOI18N
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 30, -1));

        jbAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/5x5_Mesa de trabajo 1.png"))); // NOI18N
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jbAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 30, -1));

        jbBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/5x5-03.png"))); // NOI18N
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 30, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/light-violet-color-wallpaper-4.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 690, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_jbCerrarActionPerformed

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jtPrestamos.getModel();
        try{
        if (jtPrestamos.getSelectedRow() != 1){
            dtm.removeRow(jtPrestamos.getSelectedRow());
        } else {
            JOptionPane.showMessageDialog(null, "No has seleccionado ningun prestamo");
        }
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "No has seleccionado ningun prestamo");
        }
    }//GEN-LAST:event_jbBorrarActionPerformed
    
    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        AgregarLibro3 dialog = new AgregarLibro3(new java.awt.Frame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        BuscarPrestamo2 dialog = new BuscarPrestamo2(new java.awt.Frame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jbBuscarActionPerformed
    public void mostrarLista(List<Prestamo> lista){
        try{
            Conexion con = new Conexion("jdbc:mysql://localhost/biblioteca","root","");
            String matris[][] = new String[lista.size()][4];
            AlumnoData ad = new AlumnoData(con);
            LibroData ld = new LibroData(con);
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            
            for (int i = 0; i < lista.size(); i++){
                matris[i][0] = ad.getAlumnoById(lista.get(i).getIdAlumno()).getNombre();
                matris[i][1] = ld.getLibroById(lista.get(i).getIdLibro()).getNombre();
                matris[i][2] = sdf.format(lista.get(i).getFechaPrestamo());
                matris[i][3] = sdf.format(lista.get(i).getFechaDevolucion());
            }
            
            jtPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            matris,
            new String [] {
                "Alumno", "Libro", "Fecha de prestamo", "Fecha de devolucion"
            }
            ));
            jtPrestamos.setRowHeight(30);
            jScrollPane1.setViewportView(jtPrestamos);
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "No funciono bro");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCerrar;
    private javax.swing.JLabel jlAListaPrestamos;
    public static javax.swing.JTable jtPrestamos;
    // End of variables declaration//GEN-END:variables
}
